"""init

Revision ID: 789d02f73316
Revises: 
Create Date: 2025-04-14 19:03:59.803322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789d02f73316'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Categories', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('Tasks', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Tasks', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Tasks', 'Categories', ['category_id'], ['id'])
    op.alter_column('Tasks', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Tasks', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('Categories', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
